---
- name: test
  hosts: all
  tasks:
  - name: changing the owner
    win_owner:
      path: C:\Users\Administrator\Desktop\facts.txt
      user: nazirah
      recurse: true
  - name: Giving full access
    win_acl:
      path: C:\Users\Administrator\Desktop\facts.txt
      user: nazirah
      rights: Read,Write,Modify,FullControl,Delete
      type: allow
      state: present
...