---
- name: Creating Users
  hosts: all
  tasks:
  - name: Creating a local account
    win_user:
        name: faiz
        state: present
  - name: Creating a group
    win_group:
      name: raptor
      description: Branch FLC Group
      state: present
  - name: Adding a local and domain user to a local group
    win_group_membership:
      name: raptor
      members:
      - newusers
      state: present
  - name: Create a local profile for an account
    win_user_profile:
      username: newuser
      state: present